TITLE_1: SCC0661
TITLE_2: Hipermídia e Multimídia
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro AA …</li>
    <li>Artigo BB …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SCC0661-Hipermidia-E-Multimidia
HERO_FILE: multimidia-hipermidia.png